# Generated by Django 4.1.5 on 2023-06-17 11:14

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='current_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('current', models.CharField(blank=True, max_length=300, null=True)),
                ('current_low', models.CharField(blank=True, max_length=300, null=True)),
                ('current_high', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deleted_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('node_id', models.CharField(blank=True, max_length=300, null=True)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='generator_speed_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed_high', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nodes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('location', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('sub_location', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('battery', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('user_name', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('_user_name', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='user_name', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True)),
                ('delete_status', encrypted_fields.fields.EncryptedCharField(blank=True, default='Restore', editable=False, max_length=300, null=True)),
                ('_delete_status', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='delete_status', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True)),
                ('uuid', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('_uuid', encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='uuid', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True)),
                ('time', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('date', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
                ('email', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='post_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('battery', models.CharField(blank=True, max_length=300, null=True)),
                ('faulty', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('power', models.CharField(blank=True, max_length=300, null=True)),
                ('current', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('power', models.CharField(blank=True, max_length=300, null=True)),
                ('power_high', models.CharField(blank=True, max_length=300, null=True)),
                ('power_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('theme', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='voltage_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage_low', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage_high', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='windspeed_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed_high', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
