# Generated by Django 4.1.5 on 2023-06-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_theme',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='current',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='generator_speed',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='power',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='windspeed',
        ),
    ]
