# Generated by Django 4.1.5 on 2023-06-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_delete_user_theme_remove_post_nodes_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('current', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='generator_speed_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('power', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='voltage_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='windspeed_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='post_nodes',
        ),
    ]
