# Generated by Django 4.1.5 on 2023-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_current_temp_generator_speed_temp_power_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_model',
            name='current_high',
        ),
        migrations.RemoveField(
            model_name='current_model',
            name='current_low',
        ),
        migrations.RemoveField(
            model_name='generator_speed_model',
            name='generator_speed_high',
        ),
        migrations.RemoveField(
            model_name='generator_speed_model',
            name='generator_speed_low',
        ),
        migrations.RemoveField(
            model_name='power_model',
            name='power_high',
        ),
        migrations.RemoveField(
            model_name='power_model',
            name='power_low',
        ),
        migrations.RemoveField(
            model_name='voltage_model',
            name='voltage_high',
        ),
        migrations.RemoveField(
            model_name='voltage_model',
            name='voltage_low',
        ),
        migrations.RemoveField(
            model_name='windspeed_model',
            name='windspeed_high',
        ),
        migrations.RemoveField(
            model_name='windspeed_model',
            name='windspeed_low',
        ),
        migrations.AddField(
            model_name='current_temp',
            name='current_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='current_temp',
            name='current_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generator_speed_temp',
            name='generator_speed_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generator_speed_temp',
            name='generator_speed_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='power_temp',
            name='power_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='power_temp',
            name='power_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='voltage_temp',
            name='voltage_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='voltage_temp',
            name='voltage_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='windspeed_temp',
            name='windspeed_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='windspeed_temp',
            name='windspeed_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
