# Generated by Django 4.1.5 on 2023-06-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_remove_current_temp_current_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('current_low', models.CharField(blank=True, max_length=300, null=True)),
                ('current_high', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='generator_speed_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed_high', models.CharField(blank=True, max_length=300, null=True)),
                ('generator_speed_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='power_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('power_high', models.CharField(blank=True, max_length=300, null=True)),
                ('power_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='voltage_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage_low', models.CharField(blank=True, max_length=300, null=True)),
                ('voltage_high', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='windspeed_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed_high', models.CharField(blank=True, max_length=300, null=True)),
                ('windspeed_low', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
