# Generated by Django 4.1.5 on 2023-06-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_battery_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='node_health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('health', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
