# Generated by Django 4.1.5 on 2023-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_node_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='current_temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generator_speed_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generator_speed_temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='power_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='power_temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voltage_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voltage_temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='windspeed_temp',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='windspeed_temp',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
