# Generated by Django 4.1.5 on 2023-06-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_current_model_date_current_model_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=300, null=True)),
                ('parameter', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='node_health',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='node_health',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='node_health',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
