# Generated by Django 4.1.5 on 2023-06-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_node_health_date_node_health_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_model',
            name='current_high',
        ),
        migrations.RemoveField(
            model_name='current_model',
            name='current_low',
        ),
        migrations.RemoveField(
            model_name='generator_speed_model',
            name='generator_speed_high',
        ),
        migrations.RemoveField(
            model_name='generator_speed_model',
            name='generator_speed_low',
        ),
        migrations.RemoveField(
            model_name='power_model',
            name='power_high',
        ),
        migrations.RemoveField(
            model_name='power_model',
            name='power_low',
        ),
        migrations.RemoveField(
            model_name='voltage_model',
            name='voltage_high',
        ),
        migrations.RemoveField(
            model_name='voltage_model',
            name='voltage_low',
        ),
        migrations.RemoveField(
            model_name='windspeed_model',
            name='windspeed_high',
        ),
        migrations.RemoveField(
            model_name='windspeed_model',
            name='windspeed_low',
        ),
    ]
