# Generated by Django 4.1.5 on 2023-06-27 18:36

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_remove_current_model_current_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='activate',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
