# Generated by Django 4.1.5 on 2023-06-27 18:39

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_nodes_model_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='activate',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='False', max_length=300, null=True),
        ),
    ]
