# Generated by Django 4.1.5 on 2023-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_alter_nodes_model_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='_user_name',
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
