# Generated by Django 4.1.5 on 2023-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0019_remove_nodes_model__user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='delete_status',
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='_delete_status',
            field=models.CharField(blank=True, default='Restore', max_length=300, null=True),
        ),
    ]
