# Generated by Django 4.1.5 on 2023-07-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0020_remove_nodes_model_delete_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='activate',
        ),
    ]
