# Generated by Django 4.1.5 on 2023-07-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0022_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
