# Generated by Django 4.1.5 on 2023-07-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0024_alter_nodes_model_date_alter_nodes_model_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_stamp',
            name='date_rig',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='time_stamp',
            name='time_rig',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
