# Generated by Django 4.1.5 on 2023-07-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0027_currentr_model_currentr_parameters_currentr_temp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torque_parameters',
            old_name='windspeed_high',
            new_name='torque_high',
        ),
        migrations.RenameField(
            model_name='torque_parameters',
            old_name='windspeed_low',
            new_name='torque_low',
        ),
        migrations.RenameField(
            model_name='voltageb_parameters',
            old_name='voltage_high',
            new_name='voltageB_high',
        ),
        migrations.RenameField(
            model_name='voltageb_parameters',
            old_name='voltage_low',
            new_name='voltageB_low',
        ),
        migrations.RenameField(
            model_name='voltager_parameters',
            old_name='voltage_high',
            new_name='voltageR_high',
        ),
        migrations.RenameField(
            model_name='voltager_parameters',
            old_name='voltage_low',
            new_name='voltageR_low',
        ),
        migrations.RenameField(
            model_name='voltagey_parameters',
            old_name='voltage_high',
            new_name='voltageY_high',
        ),
        migrations.RenameField(
            model_name='voltagey_parameters',
            old_name='voltage_low',
            new_name='voltageY_low',
        ),
    ]
