# Generated by Django 4.1.5 on 2023-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0028_rename_windspeed_high_torque_parameters_torque_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentr_parameters',
            old_name='current_high',
            new_name='currentR_high',
        ),
        migrations.RenameField(
            model_name='currentr_parameters',
            old_name='current_low',
            new_name='currentR_low',
        ),
    ]
