# Generated by Django 4.1.5 on 2023-07-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0029_rename_current_high_currentr_parameters_currentr_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentb_parameters',
            old_name='current_high',
            new_name='currentB_high',
        ),
        migrations.RenameField(
            model_name='currentb_parameters',
            old_name='current_low',
            new_name='currentB_low',
        ),
        migrations.RenameField(
            model_name='currenty_parameters',
            old_name='current_high',
            new_name='currentY_high',
        ),
        migrations.RenameField(
            model_name='currenty_parameters',
            old_name='current_low',
            new_name='currentY_low',
        ),
    ]
