# Generated by Django 4.1.5 on 2023-07-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0030_rename_current_high_currentb_parameters_currentb_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentb_temp',
            old_name='current',
            new_name='currentB',
        ),
        migrations.RenameField(
            model_name='currentr_temp',
            old_name='current',
            new_name='currentR',
        ),
        migrations.RenameField(
            model_name='currenty_temp',
            old_name='current',
            new_name='currentY',
        ),
        migrations.RenameField(
            model_name='voltageb_temp',
            old_name='voltage',
            new_name='voltageB',
        ),
        migrations.RenameField(
            model_name='voltager_temp',
            old_name='voltage',
            new_name='voltageR',
        ),
        migrations.RenameField(
            model_name='voltagey_temp',
            old_name='voltage',
            new_name='voltageY',
        ),
    ]
