# Generated by Django 4.1.5 on 2023-07-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0033_rename_current_currentb_model_currentb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torque_model',
            old_name='windspeed',
            new_name='torque',
        ),
        migrations.RenameField(
            model_name='torque_temp',
            old_name='windspeed',
            new_name='torque',
        ),
    ]
