# Generated by Django 4.1.5 on 2023-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0034_rename_windspeed_torque_model_torque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node_health',
            name='parameter',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
